### ISSUE TITLE
Use in CARLA

### ISSUE THREAD

**Issue by avnerbensoussan** [Simula-COMPLEX/DeepScenario#4]
Hello! 

Thank you very much for this work. 

I am trying to automate a detailed feature extraction on this dataset. 

I am totally unfamiliar with SVLSimulator, but I know CARLA pretty well. 

Do you have an idea how difficult it would be to make this dataset work on CARLA? I tried several unsuccesful things, and I am wondering if I should simply learn SVL, or keep on trying with carla...

Any suggestion? 

Thank you very much!

**Comment by chengjie-lu** [comment]
Hi @AviBen96, thanks for your interest in our work!

The DeepScenario dataset was collected and created based on SVLSimulator, so it would be easier to run it with SVL. You might know SVL is no longer officially maintained, therefore I suggest you have a look at these two simulators, which are unofficial versions of SVL: [SORA-SVL](https://github.com/YuqiHuai/SORA-SVL), [OSSDC-SIM](https://github.com/OSSDC/OSSDC-SIM).

But I think it might work if you want to run it with Carla because DeepScenario shares a similar scenario format with [OpenScenario](https://www.asam.net/standards/detail/openscenario/), which has already been supported by [Carla ScenarioRunner](https://carla-scenariorunner.readthedocs.io/en/latest/). Some work is therefore necessary: 

- Calibrate the map in Carla: Scenarios in the DeepScenario dataset run in San Francisco, so you have to add the HD map into Carla and calibrate it. All the assets of SVL are maintained by [SORA-SVL](https://github.com/YuqiHuai/SORA-SVL) and can be found in their Google drive: https://drive.google.com/drive/folders/1bv02d29z4lSB9SWzCBTUt0GjAb876oSR
- Parse scenario files correctly: Scenarios in the DeepScenario dataset were collected by timesteps, therefore, to run these scenarios, I developed [ScenarioRunner](https://github.com/Simula-COMPLEX/DeepScenario/blob/main/deepscenario-toolset/lgsvl/scenariotoolset/scenario_runner.py) that reads scenario files by timesteps and creates waypoints for each agent in the environment. A similar way is needed if you want to run the dataset with Carla.

Hope my answer can address you questions well!

**Comment by avnerbensoussan** [comment]
Thank you very much for your quick answer!

Yes, this is the reason why I thought of running it in Carla in the first place. 

I spent a few hours trying to convert it, but I figured out the investment was not worth it since I could extract the needed information without running the scenarios. 

If I ever need to run those scenarios, I look into the unofficial versions of SVL, thank you!

Thank you for the detailed answers, it is very much appreciated. 

Have a good day,
Avner

**Comment by chengjie-lu** [comment]
you are welcome:)

**Comment by Ezharjan** [comment]
> Thank you very much for your quick answer!
> 
> Yes, this is the reason why I thought of running it in Carla in the first place.
> 
> I spent a few hours trying to convert it, but I figured out the investment was not worth it since I could extract the needed information without running the scenarios.
> 
> If I ever need to run those scenarios, I look into the unofficial versions of SVL, thank you!
> 
> Thank you for the detailed answers, it is very much appreciated.
> 
> Have a good day, Avner

Me too trying to convert those `.deepscenario` files into `.xosc` so that I can run them in Esmini simulator only to find it not a smart work to do so for there is a bunch of workload.
I've also tried [SORA-SVL](https://github.com/YuqiHuai/SORA-SVL), [OSSDC-SIM](https://github.com/OSSDC/OSSDC-SIM) for hours but hard to get along well with these 2 simulators quickly.
