### ISSUE TITLE
Execution logs

### ISSUE THREAD

**Issue by ChristianBirchler** [Simula-COMPLEX/DeepScenario#5]
Hi @chengjie-lu , thanks for providing this dataset!

As far as I see, the dataset provides scenario descriptions, i.e., test scenarios that can be executed within the SVL simulator. I am wondering if there are also some execution logs about various sensor data, or do I need to re-execute the scenarios on my own to obtain this kind of data?

Thanks in advance for your help!

Best, Christian

**Comment by chengjie-lu** [comment]
Hi @ChristianBirchler, thanks for your interest in our dataset!

Our dataset is created by collecting the dynamic parameter values characterizing the objects in the driving scenarios, such as speed, position, and rotation of the ego vehicle. We didn't include sensor data in our dataset but like you say, you can replay these scenarios with the scenario toolset provided in this repository and write your scripts to collect the sensor data at runtime.

When you replay the scenarios, you have to ensure that you are using the correct version of the simulator (i.e., SVL 2021.01) because there are some map calibration issues with other versions (e.g. SVL 2021.03), which I think is caused by SVL version upgrade.

Hope this helps!
Chengjie.

**Comment by ChristianBirchler** [comment]
Hi @chengjie-lu , thank you very much for the information.

Best,
Christian
