### ISSUE TITLE
Quick Way to Visualize DeepScenario Dataset

### ISSUE THREAD

**Issue by Ezharjan** [Simula-COMPLEX/DeepScenario#6]
Hi!
Nice to see your effort in collecting data to make them a dataset using LGSVL.
Are there other common ways to visualize your `.deepscenario` files besides using SVL simulators (LGSVL, [SORA-SVL](https://github.com/YuqiHuai/SORA-SVL), [OSSDC-SIM](https://github.com/OSSDC/OSSDC-SIM))? 
Thanks~

**Comment by chengjie-lu** [comment]
Hi @Ezharjan, thanks for your interest in our dataset!

Regarding your question, the best way to visualize a scenario file (i.e., `.deepscenario`) is by using the SVL version 2021.01, however, as you might know, the SVL team no longer maintains their simulator and therefore makes it unavailable to access. 

Recently I have been using [SORA-SVL](https://github.com/YuqiHuai/SORA-SVL) to replay/visualize our scenarios, and I found that for scenarios collected in the BorregasAve map (e.g., [overtake.deepscenario](https://github.com/Simula-COMPLEX/DeepScenario/blob/main/deepscenario-toolset/tests/deepscenario/overtake.deepscenario)), everything works fine. However, for scenarios collected in the SanFrancisco map, I encountered some map calibration issues, which I think are caused by an incompatible simulator version (SORA-SVL only supports SVL version 2021.03). These days I'm recalibrating the scenarios to make them compatible with SORA-SVL, and I'll publish an updated dataset once the work is complete.

You may want to play with scenarios collected in the BorregasAve map to see how the dataset works. There are three examples provided in the dataset: https://github.com/Simula-COMPLEX/DeepScenario/tree/main/deepscenario-toolset/tests/deepscenario.

For other ways to visualize scenario files, I have not tried other methods, but you might be able to simply visualize the scenarios by plotting the objects such as ego/NPC vehicles and pedestrians, and their relative positions to gain a rough 2D picture of the scenarios. A possible idea might be [getting driving scene by timestep from a scenario](https://github.com/Simula-COMPLEX/DeepScenario/tree/main/deepscenario-toolset#usage-2-get-driving-scene-by-timestep), and then plotting the objects in each scene by using [matplotlib](https://matplotlib.org/). But I'm not sure how much effort this will cost you :)

Hope my answer can provide you with some useful information!
Chengjie.

**Comment by Ezharjan** [comment]
> Hi @Ezharjan, thanks for your interest in our dataset!
> 
> Regarding your question, the best way to visualize a scenario file (i.e., `.deepscenario`) is by using the SVL version 2021.01, however, as you might know, the SVL team no longer maintains their simulator and therefore makes it unavailable to access.
> 
> Recently I have been using [SORA-SVL](https://github.com/YuqiHuai/SORA-SVL) to replay/visualize our scenarios, and I found that for scenarios collected in the BorregasAve map (e.g., [overtake.deepscenario](https://github.com/Simula-COMPLEX/DeepScenario/blob/main/deepscenario-toolset/tests/deepscenario/overtake.deepscenario)), everything works fine. However, for scenarios collected in the SanFrancisco map, I encountered some map calibration issues, which I think are caused by an incompatible simulator version (SORA-SVL only supports SVL version 2021.03). These days I'm recalibrating the scenarios to make them compatible with SORA-SVL, and I'll publish an updated dataset once the work is complete.
> 
> You may want to play with scenarios collected in the BorregasAve map to see how the dataset works. There are three examples provided in the dataset: https://github.com/Simula-COMPLEX/DeepScenario/tree/main/deepscenario-toolset/tests/deepscenario.
> 
> For other ways to visualize scenario files, I have not tried other methods, but you might be able to simply visualize the scenarios by plotting the objects such as ego/NPC vehicles and pedestrians, and their relative positions to gain a rough 2D picture of the scenarios. A possible idea might be [getting driving scene by timestep from a scenario](https://github.com/Simula-COMPLEX/DeepScenario/tree/main/deepscenario-toolset#usage-2-get-driving-scene-by-timestep), and then plotting the objects in each scene by using [matplotlib](https://matplotlib.org/). But I'm not sure how much effort this will cost you :)
> 
> Hope my answer can provide you with some useful information! Chengjie.

Thanks!
